engines:
  fixme:
    enabled: false
  eslint:
    enabled: true
    checks:
      guard-for-in:
        enabled: false
      max-statements:
        enabled: false
      no-eval:
        enabled: false
      no-loop-func:
        enabled: false
      eqeqeq:
        enabled: false
      wrap-iife:
        enabled: false
      radix:
        enabled: false
ratings:
  paths:
    - "**.js"
exclude_paths:
- "node_modules/"
- "customlib/"
- "external/"
- "bower_components/"
- "test/"
- "samples/"
