engines:
  fixme:
    enabled: false
  eslint:
    enabled: true
    checks:
      guard-for-in:
        enabled: false
      no-eval:
        enabled: false
rules:
    max-statements: [2, 60]
    complexity: [2, 20]
ratings:
  paths:
    - "**.js"
exclude_paths:
- "node_modules/"
- "customlib/"
- "external/"
- "bower_components/"
- "test/"
- "samples/"
